### ISSUE TITLE
py_zipkin doesn't work correctly in threaded applications

### ISSUE THREAD

**Issue by kaisen** [Yelp/py_zipkin#23]
Something like this:
````python
from py_zipkin.zipkin import zipkin_span

def main():
    with zipkin_span(service_name='main', span_name='kicking_off_threads'):
        threads = []
        for i in range(5):
            t = threading.Thread(target=self.test_threading)
            threads.append(t)
            t.start()

@zipkin_span(service_name='test_threading', span_name='test_threading')
def test_threading():
    print 'in test_threading'
    return
````

In this example, only the kicking_off_threads span is logged. This is due to the fact that the zipkin context is stored in the local thread, so other threads have no knowledge of the ongoing trace. Can we/should we support this use case?

**Comment by mjbryant** [comment]
This is an interesting use case to support, but probably pretty low priority. Seems like an 'if we get around to it' thing, unless someone comes to us with a convincing use case.

There are a bunch of ways we could do this, but all would involve putting the Zipkin context in one of Python's data structures that allows data transfer between threads (e.g. a [Queue](https://docs.python.org/2/library/queue.html)) instead of or in addition to thread local storage.

**Comment by bplotnick** [comment]
I actually think we do the right thing here, which is to start 6 separate traces (one for the parent, and one for each child). I've modified the example to demonstrate:

```python
#!/usr/bin/env python
import threading
import sys
from py_zipkin.logging_helper import zipkin_logger
from py_zipkin.thread_local import get_thread_local_zipkin_attrs
from py_zipkin.zipkin import zipkin_span

def main():
    with zipkin_span(service_name='main', span_name='kicking_off_threads', transport_handler=handler, sample_rate=100):
        sys.stderr.write("parent thread: {}\n".format(get_thread_local_zipkin_attrs()))
        threads = []
        for i in range(5):
            t = threading.Thread(target=test_threading)
            threads.append(t)
            t.start()

def handler(message):
    pass

@zipkin_span(service_name='test_threading', span_name='test_threading', transport_handler=handler, sample_rate=100)
def test_threading():
    sys.stderr.write("child thread [{}]: {}\n".format(threading.current_thread().ident, get_thread_local_zipkin_attrs()))
    return

main()
```

The output is:

```
parent thread: [ZipkinAttrs(trace_id='3cf0a81809dcf852', span_id='2f4ab3cf92ea3a18', parent_span_id=None, flags='0', is_sampled=True)]
child thread [140256102168320]: [ZipkinAttrs(trace_id='697ee30376212cd4', span_id='b88eaef18f24e4db', parent_span_id=None, flags='0', is_sampled=True)]
child thread [140256093775616]: [ZipkinAttrs(trace_id='60346a3cb304e138', span_id='26f78e41d30f6b0b', parent_span_id=None, flags='0', is_sampled=True)]
child thread [140256085382912]: [ZipkinAttrs(trace_id='1a117e4f24a1d2fc', span_id='a589918ea8cbd4af', parent_span_id=None, flags='0', is_sampled=True)]
child thread [140256076990208]: [ZipkinAttrs(trace_id='db9a3daf70307c5c', span_id='f898f353f08ddd3f', parent_span_id=None, flags='0', is_sampled=True)]
child thread [140256068597504]: [ZipkinAttrs(trace_id='8412c3c544a5ee67', span_id='ff4155adb61531ce', parent_span_id=None, flags='0', is_sampled=True)]
```

We _could_ support inheritable contexts, as is done in [brave](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/CurrentTraceContext.java), which I think is what this issue is really asking for.

**Comment by bplotnick** [comment]
There is a case where we do not do the correct thing, which is the fact that the logging handler is not thread local (thanks to @dmitry-prokopchenkov for pointing this out in the zipkin gitter channel). I've created this minimal example to demonstrate:

```python
#!/usr/bin/env python
import sys
import threading
from py_zipkin.zipkin import zipkin_span

def main():
    threads = []
    for i in range(5):
        t = threading.Thread(target=test_threading)
        threads.append(t)
        t.start()

def handler(message):
    pass

def test_threading():
    with zipkin_span(service_name='main', span_name='kicking_off_threads', transport_handler=handler, sample_rate=100) as span:
        with zipkin_span(service_name='main', span_name='foobar') as child_span:
            sys.stderr.write("[{}]: root handler: {} -- child handler: {} \n".format(threading.current_thread().ident, id(span.log_handler), id(child_span.log_handler)))
    return

main()
```

The output is:

```
[140353977853696]: root handler: 140353988513072 -- child handler: 140353988662496
[140353986246400]: root handler: 140353988513072 -- child handler: 140353988662496
[140353894086400]: root handler: 140353988512456 -- child handler: 140353988662496
[140353977853696]: root handler: 140354029005736 -- child handler: 140354029005736
[140353986246400]: root handler: 140354028300552 -- child handler: 140354029005736
```

**Comment by dmitry-prokopchenkov** [comment]
@bplotnick I think here we should 
1) remove log_handler and zipkin_loger
2) place client_spans list in loggingContext
3) save loggingContext on creating to thread_local where child spans can get it (as it was done for zipkin_attrs)

And I might implement this. 
I believe this way is similar to how Inheritable trace [contexts](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/CurrentTraceContext.java) work in brave. What do you think?

**Comment by bplotnick** [comment]
@dmitry-prokopchenkov This sounds like a pretty good plan. I like the idea of storing the trace context (basically just `ZipkinLoggingContext`) to thread local. I think you meant non-inheritable trace contexts in brave, but yeah this sounds exactly like that. 

I would not get rid of the log handler stuff entirely, though. It is sometimes nice to be able to just say `zipkin_logger.debug(some_dict_form_of_span)`. We've seen a few cases of people using py_zipkin this way. I think it would be enough to make the log handler a singleton that logs to the thread local trace context (so in `emit` instead of `self.store_local_span()` it would be `thread_local_trace_context().store_local_span()`).

If you want to take a stab at this, feel free! Let me know if you need any help with it.

**Comment by bplotnick** [comment]
@dmitry-prokopchenkov on second thought, i'm starting to think that it might be better to just remove the log handler stuff. It would not only help solve this issue, but it would also simplify the API.

If it is simpler to remove the log handler, i'd say go for it. I opened #61 to discuss the removal further in case there are any objections.

**Comment by dmitry-prokopchenkov** [comment]
I had to create a workaround for this to avoid problems with multithreading before we improve py_zipkin:
```
from flask import g

import py_zipkin.logging_helper as lh


class FakeZipkinLogger:
    def addHandler(self, handler):
        if lh.null_handler != handler:
            g._zipkin_log_handler = handler

    def removeHandler(self, handler):
        if lh.null_handler != handler:
            g._zipkin_log_handler = None

    def __getattr__(self, name):
        if name == 'handlers':
            return self._handlers()

    def _handlers(self):
        handler = g.get('_zipkin_log_handler', lh.null_handler)
        return [handler]


def forge_zipkin_logger():
    lh.zipkin_logger = FakeZipkinLogger()
```
It is for Flask and based on its g context object, but it can be easily reworked for using thread local. Please note that forge_zipkin_logger() should be called before imports from py_zipkin library.

**Comment by drolando** [comment]
This is now supported as explained at https://github.com/Yelp/py_zipkin#using-in-multithreading-evironments
