### ISSUE TITLE
how to use py_zipkin?

### ISSUE THREAD

**Issue by hugoren** [Yelp/py_zipkin#62]
I read all kinds of documents, still don't understand, how to use py_zipkin?
help me

**Comment by bplotnick** [comment]
@hugoren We're happy to help, but github issues are meant for feature requests, bugs, etc. If you have some questions, please feel free to stop by the zipkin gitter at https://gitter.im/openzipkin/zipkin

**Comment by hugoren** [comment]
Since open source, why isn't there a better and more detailed documentation

**Comment by hugoren** [comment]
No wonder so few people use it

**Comment by adriancole** [comment]
We use gitter to elaborate open ended questions because it doesnt spam
everyone watching the repo. This in no way suggests documentation cant
improve, just we cant read your mind either. I know it is frustrating to
not have everything understood when you enter a project, but lashing out in
frustration isnt a great way to proceed. These are volunteers and some are
taking time away from family rest etc to respond. Lashing out is something
we sometimes endure but it isnt acceptable conduct. TL;DR if you want to
have help, please join gitter. If you were just using us to vent
frustration, I guess we are done.
