### ISSUE TITLE
Sample Data or example application showing multiple spans

### ISSUE THREAD

**Issue by viperfx** [Yelp/py_zipkin#7]
Hi,

Is there example traces or sample data I can download to get an idea of how to use the attributes in zipkin? I wanted to trace how a particular event is processed through our components. Those events have unique identifiers and I am wondering how I should be passing them in to zipkin. I am going to be using python and Go instrumentation for our components. Just wondering about best practices etc.

I have been tracing for some time now and I can't seem to see multiple spans with this lib. I just see one span for my services. I even set cutom span and parent_span ID's to be passed in.

Some sample code:
A task being queued 
```
        zattr = ZipkinAttrs(trace_id=self.message.id.replace('-',''), span_id=self.message.id.replace('-',''), parent_span_id=None, flags=None, is_sampled=False)
        with zipkin_span(
            service_name='trace',
            span_name="stage2:consumer",
            zipkin_attrs=zattr,
            transport_handler=transport_handler,
            sample_rate=0.1,
            port=42,
        ):
            self._task.delay(self.message)
```
A worker executing the task
```
        if method is not None:
            zattr = ZipkinAttrs(trace_id=self.message.id.replace('-',''), span_id=generate_random_64bit_string(), parent_span_id=self.message.id.replace('-',''), flags=None, is_sampled=False)
            with zipkin_span(
                service_name='trace',
                span_name="stage3:worker",
                zipkin_attrs=zattr,
                transport_handler=transport_handler,
                sample_rate=0.1,
                port=42,
            ):
                method()
```

I should be seeing a root trace and 2 spans right? or have I misunderstood something fundamental?

Thanks,

**Comment by kaisen** [comment]
There will be more explicit documentation in the future!

The `zipkin_attrs` and `sample_rate` params should only be used for the root span of the trace. Assuming that the worker executing the task is in the context of the root zipkin_span, you can remove the `zipkin_attrs` and `sample_rate` params from the second zipkin_span. py_zipkin uses threading to keep track of an ongoing trace so the zipkin_attrs will be generated for you.

**Comment by mjbryant** [comment]
@viperfx Could you give any more information as to how your code is structured? It's hard to tell just from these examples.

One thought that crossed my mind was it might be how your ZipkinAttrs are interacting with the sampling rate. You're specifying `is_sampled=False` in your ZipkinAttrs and then sampling at a very low rate (0.1% - `sample_rate` is an int between 0.0 and 100.0, where the latter is 100% sampling). If you're doing this at every level of your program, that means you're sampling independently at each of them. I.e. 0.1% of "stage3:worker" requests will have spans generated for them, _regardless of whether the corresponding "stage2:worker" request was sampled_. Ideally, you'd instead sample at the uppermost level, then propagate whether it was sampled to the lower levels.

**Comment by viperfx** [comment]
Oh darn. I had missed that and thought it was 10% because the example has 0.05. 

So, overall, the flow of the data is that,

- We communicate through a TCP socket to get events from an external service through a Go script.
- Events are sent to a RabbitMQ queue from the Go Script
- Events are picked up from the queue by a consumer
- The events are then wrapped in a celery task before before being queued up, different queue destinations for different types of data. We use RabbitMQ for the broker too. (current being instrumented)
- The task get executed by the work. (Currently being instrumented).

@kaisen I don't think the context is shared between when the root is created and when the trace is sent before the worker executes.

**Comment by mjbryant** [comment]
@viperfx what exactly are you doing to "map the two spans to one trace". Do they have the same trace ID? Based on your sample code, they should, because each step is deriving it from what I assume is a static variable: `self.message.id`. Then you also need the "stage3:worker: span(s) to have a parent span ID of the correct "stage2:worker" span, which again it should based on your examples.

If these two things are true, there's not much else this library is meant to do. Can you paste some example spans?

**Comment by viperfx** [comment]
Here is a JSON from a trace
```
[
  {
    "traceId": "3a825b55a48fcd40",
    "id": "0356ae10ec0df0bc",
    "name": "stage2:consumer",
    "timestamp": 1474749229934936,
    "duration": 2369,
    "annotations": [
      {
        "timestamp": 1474749229934936,
        "value": "sr",
        "endpoint": {
          "serviceName": "rtr",
          "ipv4": "192.168.0.140"
        }
      },
      {
        "timestamp": 1474749229937305,
        "value": "ss",
        "endpoint": {
          "serviceName": "rtr",
          "ipv4": "192.168.0.140"
        }
      }
    ]
  }
]
```

Here are the traces I see in the UI. All one spans.
<img width="1527" alt="screen shot 2016-09-26 at 6 52 18 am" src="https://cloud.githubusercontent.com/assets/328257/18831813/dc9dd91c-83b5-11e6-9bad-144df4e6a3a1.png">

Something to note is that my EventID's look like this:
```
2bca7f21-f922-411b-9d2d-00ec4df8bb49
```

I had an error if I fed that directly as a trace_id. So I had to clip it to 16 characters, which might have resulted in overlapping trace_id's.

<img width="912" alt="screen shot 2016-09-26 at 6 56 24 am" src="https://cloud.githubusercontent.com/assets/328257/18831914/74d12126-83b6-11e6-85d9-1cd84ca236c3.png">

**Comment by mjbryant** [comment]
I think I may have spotted the problem, assuming you're still using the same pattern to generate `ZipkinAttrs`. If `ZipkinAttrs` are passed in, but `is_sampled` is set to false, the decorator will generate new attributes for the span, which will override the `parent_span_id` you constructed the the message ID. [Relevant code](https://github.com/Yelp/py_zipkin/blob/v0.1.1/py_zipkin/zipkin.py#L168).

This is intentional - it supports the use case of sampling a component of your system independently of its upstream components. I.e., you might want to produce "stage3:worker" spans at a different rate than "stage2:consumer" spans, so you sample an additional % of "stage3:worker" spans in the cases where the "stage2:consumer" stage isn't sampled.

The solution to this is to get rid of the `sample_rate` kwarg in the "stage3:worker" span, then set the `is_sampled` part of the `ZipkinAttrs` in "stage3:worker" to True in the cases where the corresponding "stage2:consumer" is sampled. Like @kaisen said, you really need a way to propagate this information. Can you add additional information into the `message` payload?

In the absence of the ability to propagate, you can at least test this by sampling everything in the "stage2:consumer" phase and just setting `is_sampled=True` in the "stage3:worker" phase.

**Comment by viperfx** [comment]
Okay, I will try this. Should I expect a trace with 2 spans? 

@mjbryant Do you have any suggestions for the error I pasted and about how to use the full EventID with clipping it?

**Comment by viperfx** [comment]
@mjbryant `self.message` is a dict. One of its keys is the `id`. Yes, I can add more info. Not sure what you mean though, I don't see a way to add info to the traces with this library. I would love to do that, such as the TaskName, the task payload etc.

**Comment by mjbryant** [comment]
@viperfx if the message is a dict, you can propagate context just like you would through HTTP headers. Then you can decouple the Zipkin IDs from the message IDs. So in "stage2:consumer" you'd do something like:

```python
zattrs = py_zipkin.zipkin.create_attrs_for_span()
self.message.update({
  'X-B3-TraceId': zattrs.trace_id,
  'X-B3-ParentSpanId': zattrs.span_id,
  'X-B3-SpanId': py_zipkin.util.generate_random_64bit_string(),
  'X-B3-Sampled': '1' if zattrs.is_sampled else '0',
})
with zipkin_span(
    service_name='trace',
    span_name='stage2:consumer',
    zipkin_attrs=zattr,
    transport_handler=transport_handler,
    port=42,
):
  self._task.delay(self.message)
```

and in "stage3:worker", you'd check the message for the "X-B3-" attributes and use them to reconstruct the `ZipkinAttrs`. For example:

```python
zattrs = ZipkinAttrs(
  self.message['X-B3-TraceId'],
  self.message['X-B3-SpanId'],
  self.message['X-B3-ParentSpanId'],
  '0',
  self.message['X-B3-Sampled']
)
```

This is essentially recreating the `inject/extract` API for HTTP header propagation that's the standard for Zipkin (since so many things communicate over HTTP).

And finally, no, I don't have a good way off the top of my head to generate trace IDs from message IDs better. But do you really need to generate trace IDs from message IDs? Just generate random ones. If you really do, I'd suggest something like stripping dashes and using the 16 trailing characters, or stripping dashes, and hashing the hex string to a 16 character digest. There are probably tons of options.

**Comment by viperfx** [comment]
@mjbryant Okay. Now I can see 2 spans, Thanks!

So how does the sampling work in this scenario?

**Comment by mjbryant** [comment]
@viperfx the sampling works by sampling at the outermost layer ("stage2:consumer" in your case) and propagating the sampling decision there by setting the "X-B3-Sampled" header (or message dict key) to the worker. In the example I gave above you'd simply pass a kwarg, `sample_rate=50.0`, for example, to `create_attrs_for_span`.

**Comment by mjbryant** [comment]
Closing this issue, as I believe we addressed the underlying issue in the submitter's code.
